# Generated by Django 5.2.3 on 2025-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('period', models.IntegerField(choices=[(0, 'One Time'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')])),
                ('type', models.IntegerField(choices=[(0, 'QR Code'), (1, 'Entrance')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='challenges')),
            ],
        ),
    ]
