# Generated by Django 5.2.3 on 2025-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(),
        ),
    ]
