# Generated by Django 5.2.3 on 2025-06-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_challenge_end_date_alter_challenge_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
