# Generated by Django 5.2.3 on 2025-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_quiz_remove_challenge_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(),
        ),
    ]
