# Generated by Django 5.2.3 on 2025-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_quiz_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
