# Generated by Django 5.2.3 on 2025-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_remove_quizanswer_answer_quizanswer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
