# Generated by Django 5.2.3 on 2025-06-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_quiz_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='date',
        ),
    ]
