# Generated by Django 5.2.3 on 2025-06-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_remove_quizanswer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='events')),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='period',
            field=models.IntegerField(choices=[(0, 'Jednorazowe'), (1, 'Dzienne'), (2, 'Tygodniowe'), (3, 'Miesięczne')]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kod QR'), (1, 'Wejście')]),
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
        ),
    ]
