# Generated by Django 5.2.3 on 2025-07-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_alter_challenge_period_alter_challenge_type_pets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
